version: '3.9'

services:
  minio:
    image: quay.io/minio/minio:latest
    network: host
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: 'minio_root'
      MINIO_ROOT_PASSWORD: '1qazxsw2'
      MINIO_CONSOLE_ADDRESS: ':9001'
      MINIO_ADDRESS: ':9000'
    command: minio server /data

volumes:
  minio_storage: {}
